export const colors = { 
    SELECTED_PRIMARY: '#26f',
    DARKER_PRIMARY: '#15d',
    LIGHTER_PRIMARY: '#57f',
    DARKEST_PRIMARY: '#015',
    LIGHTEST_PRIMARY: '#99f',
    WHITE: '#FFF',
    LIGHT_GRAY: '#CCC',
    DARK_GRAY: '#333',
    MID_GRAY: '#777',
    DARK_MAGENTA: '#808',
    DARK_CYAN: '#078',
    GREEN: '#108030',
    PC_BACKGROUND:'#CC6A00',
    GARD_BACKGROUND:'#BDD16B',
    CLEAN_BACKGROUND:"#80C3BF"

}