export const images = {
    history: require("../assets/images/history-icon.png"),
    marketplace: require("../assets/images/shop-icon.png"),
    chat: require("../assets/images/message-icon.png"),
    logo: require("../assets/images/placeholder.png"),
    placeholder: require("../assets/images/placeholder.png"),
    profile: require("../assets/images/profile-icon.png"),
    carService: require("../assets/images/CAR_SERV.png"),
    computerService: require("../assets/images/PC_SERV.jpeg"),
    gardeningService: require("../assets/images/GARD_SERV.png"),
    cleaningService: require("../assets/images/CLEAN_SERV.png"),
    star: require("../assets/images/star-icon.png"),
    emptyStar: require("../assets/images/black-star-icon.png"),
    expand: require("../assets/images/plus-round-line-icon.png"),
    shrink: require("../assets/images/minus-round-line-icon.png"),
    attachment: require("../assets/images/attachment-pin-icon.png"),
    login: require("../assets/images/login-icon.png"),
    register: require("../assets/images/sign-up-icon.jpg"),
    backArrow: require("../assets/images/arrow-left-icon.png"),
    address: require("../assets/images/address-location-icon.png"),
    support: require("../assets/images/headphone-headset-icon.png"),
    information: require("../assets/images/info-circle-icon.png"),
    logout: require("../assets/images/logout-line-icon.png"),
    flag_jo: require("../assets/images/jordan-flag-icon.png"),
    check: require("../assets/images/check-icon.png"),
    loading: require("../assets/images/loading.gif"),
} 